import {files,endings,policyNotes,commonAfterword,caseResolution} from './content.js';
import {KEY,times,events,evidence,fresh,accessible,checkKey,checkTimeline,endingFor,snapshot,validate,claimTexts,refIds,judgments,backupReasons,claimReasons,checkBackup,prepareHandoff,canFinalize,summaryFor} from './domain.js';
const app=document.querySelector('#app');
const icon=(name)=>`<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${({pc:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/>',file:'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6m-6 4h6"/>',folder:'<path d="M3 6h7l2 2h9v12H3z"/>',trash:'<path d="M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',photo:'<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8" cy="8" r="1"/><path d="m3 18 6-7 4 4 3-4 5 6"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/>',board:'<rect x="4" y="4" width="16" height="17" rx="2"/><path d="M8 9h8m-8 4h8m-8 4h5"/>'})[name]||''}</svg>`;
function initialStart(){app.innerHTML=`<main class="start"><header class="topline"><div class="brand">${icon('pc')}<span>LOCAL ARCHIVE / 01</span></div><span class="mono">2026.04.21</span></header><div class="start-main"><section><div class="eyebrow">AN INTERACTIVE MYSTERY</div><h1>중고 컴퓨터의<br>비밀</h1><div class="subtitle">지워지지 않은 밤</div><p class="lead">낡은 컴퓨터 하나를 샀다.<br>이전 주인은 사라졌고, 기록은 남아 있었다.<br>지워진 파일을 복원하고, 그날 밤을 연결하세요.</p><div class="actions"><button class="primary" id="new">새 조사 시작 ↗</button><button id="continue" disabled>이어하기</button></div><p class="muted" style="font-size:12px;margin-top:22px">첫 번째 사건 · 1인 플레이 · 예상 30–60분</p></section><aside><div class="preview-note"><div class="note-bar"><span>읽어주세요.txt</span><span>— &nbsp; □ &nbsp; ×</span></div><div class="note-body">이 컴퓨터를 받으셨다면,<br>인터넷에 연결하기 전에<br><strong>휴지통부터 확인해 주세요.</strong><div class="signature">— 윤서</div></div><div class="note-bottom">이전 사용자가 남긴 문서 &nbsp; / &nbsp; 로컬 사본</div></div><div class="evidence-label">SOME RECORDS REFUSE TO DISAPPEAR.</div></aside></div><footer class="start-foot"><span>웹페이지 안의 가상 컴퓨터를 조사합니다.<br>실제 PC의 파일이나 메일을 읽거나 바꾸지 않습니다.</span><span>어두운 분위기와 짧은 화면 변화가 있습니다.<br>큰 소리의 갑작스러운 놀람 연출은 없습니다.</span><button id="settings" class="ghost">설정 · 도움말</button></footer></main>`;document.querySelector('#new').onclick=()=>{app.innerHTML='<main class="desktop"><header class="desk-head">해온기록 · 로컬 작업 공간</header><section class="workspace"><div class="icons">'+[['file','읽어주세요.txt'],['lock','작업기록'],['photo','사진'],['folder','복원된 파일'],['mail','메일함'],['trash','휴지통']].map(([i,n])=>`<button class="desk-icon">${icon(i)}${n}</button>`).join('')+'</div><div class="desk-watermark">지워지지<br>않은 밤.</div></section><footer class="taskbar">LOCAL · 오프라인 사본</footer></main>'}}

let legacyNotice='',state=fresh(),loadIssue='',conflict=false,saveOK=true,view='start',windows=[],z=10,selected=null,toastTimer,audioContext;
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));else if(localStorage.getItem('used-pc-mystery:ep1:v2'))legacyNotice='이야기와 퍼즐이 개정되었습니다. 이전 버전의 저장은 보존되어 있으며, 이번 버전은 새 조사로 시작합니다.';}catch(e){loadIssue='저장된 진행을 불러오지 못했습니다. 기존 기록을 보존한 채 새 조사를 시작하거나 설정에서 기록을 확인할 수 있습니다.';saveOK=false;}
const modal=document.querySelector('#modal');
let backdropPress=false;
function outsideModal(event){const r=modal.getBoundingClientRect();return event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom;}
modal.addEventListener('pointerdown',event=>{backdropPress=event.target===modal&&outsideModal(event);});
modal.addEventListener('pointercancel',()=>{backdropPress=false;});
modal.addEventListener('click',event=>{const dismiss=backdropPress&&event.target===modal&&outsideModal(event);backdropPress=false;if(dismiss)modal.close();});
modal.addEventListener('close',()=>{backdropPress=false;});

const F=id=>files.find(x=>x.id===id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const goals=['휴지통의 조각과 접수사진을 비교해 작업기록을 여세요.','출입기록과 시계점검을 비교해 실제 퇴실 시각을 찾으세요.','자료 묶음 ID를 대조해 인계 순서대로 원래 번호를 연결하세요.','원본과 백업을 대조하고 두 후보의 탈락 사유를 찾으세요.','증언자의 요청을 확인하고 사건 순서와 세 주장을 검토하세요.','마지막 메일과 처리 방침을 확인하고 전달 범위를 결정하세요.'];
const folderNames={photos:'사진',trash:'휴지통',restored:'복원된 파일',mail:'메일함',work:'작업기록',archive:'복구보관함',outbox:'발신보관함',backup:'인계 백업',board:'기록보드',timeline:'사건 재구성'};
function persist(){if(conflict||loadIssue)return;state.revision=Date.now();try{localStorage.setItem(KEY,JSON.stringify(state));saveOK=true;}catch(e){saveOK=false;toast('진행을 저장하지 못했습니다. 이 창에서는 계속할 수 있지만 닫으면 진행이 사라질 수 있습니다.');}updateStatus();}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.style.display='none',5000);}
function applySettings(){document.documentElement.style.fontSize=state.settings.size===125?'20px':'16px';document.body.classList.toggle('reduce-motion',state.settings.motion);}
function sound(){if(!state.settings.sound||document.hidden)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=420;g.gain.setValueAtTime(.025,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.13);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.14);}catch{}}
function updateStatus(){const el=document.querySelector('#save-status');if(el)el.textContent=conflict?'저장 충돌':saveOK?'자동 저장됨':'저장 불가';}
function showModal(title,html,setup){if(modal.open)modal.close();modal.innerHTML=`<div class="modal-head"><h2>${esc(title)}</h2><button aria-label="닫기" id="modal-close">×</button></div><div class="modal-body">${html}</div>`;modal.querySelector('#modal-close').onclick=()=>modal.close();modal.showModal();setup?.();}
function confirmAction(title,text,fn,label='확인'){showModal(title,`<p>${esc(text)}</p><div class="actions"><button class="primary" id="confirm-action">${label}</button><button id="cancel-action">돌아가기</button></div>`,()=>{modal.querySelector('#confirm-action').onclick=()=>{modal.close();fn();};modal.querySelector('#cancel-action').onclick=()=>modal.close();});}
function start(){rememberWindowViews();view='start';initialStart();const n=document.querySelector('#new');n.onclick=()=>{if(state.started||loadIssue)confirmAction('새 조사 시작','현재 조사 진행을 처음부터 시작할까요? 이미 본 엔딩 기록은 유지됩니다.',newGame,'새 조사 시작');else newGame();};const c=document.querySelector('#continue');c.disabled=!state.started;c.onclick=()=>{view=state.ending?'ending':'desktop';state.ending?renderEnding():(desktop(),state.handoffPrepared?finalReview():null);};document.querySelector('#settings').onclick=settings;if(legacyNotice){const p=document.createElement('p');p.className='alert';p.textContent=legacyNotice;document.querySelector('.start-main section').append(p);}if(loadIssue){const e=document.createElement('p');e.className='alert';e.textContent=loadIssue;document.querySelector('.start-main section').append(e);}applySettings();}
function newGame(){const settings=state.settings;state=fresh(state.endingsSeen);state.settings=settings;state.started=true;legacyNotice='';loadIssue='';conflict=false;persist();windows=[];desktop();}
function settings(){showModal('설정 · 도움말',`<p class="muted">파일은 더블클릭하거나 선택 후 Enter로 열 수 있습니다. 창의 제목을 끌어 이동하고, 오른쪽 아래 모서리를 끌어 크기를 조절하세요.</p><div class="settings-row"><label for="size">글자 크기</label><select id="size"><option value="100">100%</option><option value="125">125%</option></select></div><div class="settings-row"><label for="motion">모션 줄이기</label><input id="motion" type="checkbox"></div><div class="settings-row"><label for="sound">작은 조작음</label><input id="sound" type="checkbox"></div><p class="muted">소리 없이 모든 단서를 확인할 수 있습니다. 진행은 이 브라우저에만 저장됩니다.</p><p id="storage-info">${conflict?'다른 탭의 변경을 확인해야 합니다.':saveOK?'자동 저장을 사용할 수 있습니다.':'자동 저장을 사용할 수 없습니다.'}</p><div class="actions"><button id="reset">현재 조사 초기화</button><button id="delete">개인 기록 전체 삭제</button></div>`,()=>{const size=modal.querySelector('#size');size.value=state.settings.size;size.onchange=()=>{state.settings.size=Number(size.value);applySettings();persist();};for(const key of ['motion','sound']){const el=modal.querySelector('#'+key);el.checked=state.settings[key];el.onchange=()=>{state.settings[key]=el.checked;applySettings();persist();sound();};}modal.querySelector('#reset').onclick=()=>confirmAction('조사 초기화','현재 진행을 처음부터 시작합니다. 이미 본 엔딩 기록은 유지됩니다.',newGame);modal.querySelector('#delete').onclick=()=>confirmAction('개인 기록 전체 삭제','이 게임의 진행과 엔딩 기록을 모두 삭제할까요?',()=>{try{localStorage.removeItem(KEY)}catch{}state=fresh();loadIssue='';conflict=false;windows=[];start();});});}
function desktop(){rememberWindowViews();view='desktop';app.innerHTML=`<main class="desktop"><header class="desk-head"><div class="brand">${icon('pc')}<span>해온기록 <span class="muted">/ 개인 보관함</span></span></div><span class="mono muted">LOCAL SESSION &nbsp; 2026.04.21</span></header><section class="workspace"><div class="icons"></div><div class="desk-watermark">지워지지<br>않은 밤.</div><div id="windows"></div></section><footer class="taskbar"><button id="home" title="시작 화면">${icon('pc')}</button><div class="tasks"></div><span class="task-status" id="save-status"></span><span class="task-status">${state.policy?state.policy==='protect'?'식별정보 보호':'식별정보 유지':'로컬 사본'}</span><button id="help">설정</button></footer></main>`;const items=[['F01','file','읽어주세요.txt'],['work',state.stage?'folder':'lock','작업기록'],['photos','photo','사진'],['restored','folder','복원된 파일'],['mail','mail','메일함'],['board','board','기록보드'],['trash','trash','휴지통']];document.querySelector('.icons').innerHTML=items.map(([id,i,n])=>`<div style="position:relative"><button class="desk-icon" data-open="${id}">${icon(i)}<span>${n}</span></button></div>`).join('');document.querySelectorAll('[data-open]').forEach(el=>{el.onclick=()=>{document.querySelectorAll('.desk-icon').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');selected=el.dataset.open;};el.ondblclick=()=>openItem(el.dataset.open);el.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();openItem(el.dataset.open)}}});document.querySelector('#home').onclick=start;document.querySelector('#help').onclick=settings;renderWindows();updateStatus();}
function currentAction(){if(state.stage<3)lock(state.stage);else if(state.stage===3)backupPuzzle();else if(state.stage===4){state.policy?openFolder('timeline'):witness();}else handoffAction();}
function handoffAction(){if(state.stage!==5)return;if(!state.opened.includes('F10')){openFile('F10');return;}finalReview();}
function finalActionLabel(){return state.handoffPrepared?'최종 검토':state.opened.includes('F10')?'전달 내용 검토':'마지막 메일 확인';}
function currentGoal(){return state.stage===5?(state.handoffPrepared?'준비된 자료와 신원 처리 방침을 검토하고 전달 범위를 선택하세요.':state.opened.includes('F10')?'전달 내용 검토를 눌러 인계를 준비하세요.':'마지막 메일을 확인하세요. 사건 재구성은 완료된 상태로 유지됩니다.'):goals[state.stage];}
function openItem(id){if(id.startsWith('F'))openFile(id);else openFolder(id);}
function addWindow(id,title){let w=windows.find(x=>x.id===id);if(w){w.min=false;w.z=++z;}else{w={id,title,x:Math.min(245+windows.length*22,innerWidth-640),y:45+(windows.length%3)*27,z:++z,min:false,preset:'default'};windows.push(w);}const visible=windows.filter(x=>!x.min);if(visible.length>4)visible.sort((a,b)=>a.z-b.z)[0].min=true;renderWindows();sound();}
function openFile(id){if(!accessible(id,state)){toast('먼저 이전 보관함을 복구해 주세요.');return;}if(!state.opened.includes(id)){state.opened.push(id);persist();if(id==='F05')toast('로컬 예약 메모 · 시계점검 조각은 휴지통에 남겨 두었습니다.');if(id==='F10')toast('로컬 예약 메모 · 추가 백업을 확인해 주세요.');}if(view!=='desktop'||id==='F10'&&state.stage===5)desktop();addWindow(id,F(id).title);}
function openFolder(id){if(id==='work'&&state.stage<1)return lock(0);if(id==='archive'&&state.stage<2)return lock(1);if(id==='outbox'&&state.stage<3)return lock(2);if(id==='backup'&&state.stage<4)return backupPuzzle();if(id==='timeline'&&(!state.policy||state.stage<4))return witness();addWindow(id,folderNames[id]||id);}
function rememberWindowViews(){
 document.querySelectorAll('#windows .window[data-window-id]').forEach(el=>{
  const w=windows.find(item=>item.id===el.dataset.windowId);if(!w)return;
  const content=el.querySelector('.window-content');if(!content)return;
  w.view={top:content.scrollTop,left:content.scrollLeft,details:[...content.querySelectorAll('details')].map(item=>item.open),tables:[...content.querySelectorAll('.table-wrap')].map(item=>item.scrollLeft)};
 });
}
function restoreWindowView(el,w){
 const content=el.querySelector('.window-content');if(!w.view)return;
 content.querySelectorAll('details').forEach((item,index)=>{item.open=!!w.view.details[index];});
 content.querySelectorAll('.table-wrap').forEach((item,index)=>{item.scrollLeft=w.view.tables[index]||0;});
 content.scrollTop=w.view.top;content.scrollLeft=w.view.left;
}

function renderWindows(){
 const root=document.querySelector('#windows');if(!root)return;rememberWindowViews();root.innerHTML='';
 for(const w of windows.filter(x=>!x.min)){
  const el=document.createElement('section');el.className='window';el.dataset.windowId=w.id;el.setAttribute('aria-label',w.title);el.style.zIndex=w.z;
  const workspace=document.querySelector('.workspace'),width=workspace.clientWidth,height=workspace.clientHeight;
  let winWidth=Math.min(w.width||610,width-24),left=Math.max(12,Math.min(w.x,width-winWidth-12)),top=Math.max(12,Math.min(w.y,height-240));
  if(w.preset==='left'||w.preset==='right'){winWidth=(width-40)/2;left=w.preset==='left'?12:width/2+8;top=14;}
  if(w.preset==='max'){left=12;top=12;winWidth=width-24;}
  if(innerWidth<=900){left=10;top=15;winWidth=width-20;}
  el.style.left=left+'px';el.style.top=top+'px';el.style.width=winWidth+'px';el.style.maxHeight=(height-top-12)+'px';
  if(w.preset==='max')el.style.height=(height-top-12)+'px';else if(w.height)el.style.height=Math.min(w.height,height-top-12)+'px';
  el.innerHTML=`<div class="titlebar"><span>${esc(w.title)}</span><button data-min aria-label="최소화">−</button><button data-max aria-label="크게 보기">□</button><button data-close aria-label="창 닫기">×</button></div><div class="window-content"></div><div class="window-footer"><button class="window-resize" aria-label="창 크기 조절" title="드래그하여 크기 조절 · 방향키로도 조절할 수 있습니다">◢</button></div>`;
  root.append(el);el.onpointerdown=()=>{w.z=++z;el.style.zIndex=w.z};
  el.querySelector('[data-close]').onclick=()=>{windows=windows.filter(x=>x!==w);renderWindows()};
  el.querySelector('[data-min]').onclick=()=>{w.min=true;renderWindows()};
  el.querySelector('[data-max]').onclick=()=>{w.preset=w.preset==='max'?'default':'max';renderWindows()};
  const bar=el.querySelector('.titlebar');
  bar.onpointerdown=e=>{if(e.target.closest('button')||innerWidth<=900)return;const sx=e.clientX,sy=e.clientY,bx=el.offsetLeft,by=el.offsetTop;w.width=el.offsetWidth;w.height=el.offsetHeight;w.preset='default';bar.setPointerCapture(e.pointerId);bar.onpointermove=ev=>{w.x=Math.max(0,Math.min(bx+ev.clientX-sx,width-el.offsetWidth));w.y=Math.max(0,Math.min(by+ev.clientY-sy,height-el.offsetHeight));el.style.left=w.x+'px';el.style.top=w.y+'px';el.style.maxHeight=(height-w.y)+'px';};const done=()=>{bar.onpointermove=null;bar.onpointerup=null;bar.onpointercancel=null};bar.onpointerup=done;bar.onpointercancel=done;};
  const grip=el.querySelector('.window-resize');
  const resize=(nextWidth,nextHeight)=>{const maxWidth=width-el.offsetLeft-10,maxHeight=height-el.offsetTop-10;w.width=Math.max(Math.min(360,maxWidth),Math.min(nextWidth,maxWidth));w.height=Math.max(Math.min(240,maxHeight),Math.min(nextHeight,maxHeight));w.x=el.offsetLeft;w.y=el.offsetTop;w.preset='default';el.style.width=w.width+'px';el.style.height=w.height+'px';el.style.maxHeight=maxHeight+'px';};
  grip.onpointerdown=e=>{e.preventDefault();const sx=e.clientX,sy=e.clientY,bw=el.offsetWidth,bh=el.offsetHeight;grip.setPointerCapture(e.pointerId);el.classList.add('resizing');grip.onpointermove=ev=>resize(bw+ev.clientX-sx,bh+ev.clientY-sy);const done=()=>{grip.onpointermove=null;grip.onpointerup=null;grip.onpointercancel=null;el.classList.remove('resizing')};grip.onpointerup=done;grip.onpointercancel=done;};
  grip.onkeydown=e=>{const delta={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]}[e.key];if(!delta)return;e.preventDefault();resize(el.offsetWidth+delta[0],el.offsetHeight+delta[1]);};
  renderContent(el.querySelector('.window-content'),w.id);restoreWindowView(el,w);
 }
 const tasks=document.querySelector('.tasks');tasks.innerHTML=windows.map(w=>`<button data-task="${w.id}" style="${w.min?'opacity:.6':''}">${esc(w.title)}</button>`).join('');tasks.querySelectorAll('button').forEach(b=>b.onclick=()=>{const w=windows.find(x=>x.id===b.dataset.task);w.min=false;w.z=++z;renderWindows()});
}

function actionButton(root,label,fn,primary=false){const b=document.createElement('button');b.textContent=label;if(primary)b.className='primary';b.onclick=fn;root.append(b);return b;}
function fileRow(root,id){const b=document.createElement('button');b.className='file-row';b.innerHTML=icon(id.startsWith('F')?(id==='F03'||id==='F15'?'photo':id==='F04'||id==='F10'?'mail':'file'):'folder')+`<span>${esc(F(id)?.title||folderNames[id]||id)}</span><small>열기 ↗</small>`;b.onclick=()=>openItem(id);root.append(b);}
function tableHTML(rows){return `<div class="table-wrap"><table><thead><tr>${rows[0].map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function renderContent(root,id){if(id==='backup'&&state.stage===3){renderBackup(root);return;}const lockIndex=['work','archive','outbox'].indexOf(id);if(lockIndex>=0&&state.stage===lockIndex){renderLock(root,id,lockIndex);return;}if(id.startsWith('F')){const f=F(id);root.innerHTML=`<div class="file-meta">${id} / ${id==='F04'||id==='F10'?'저장된 메일 · 실제 발송 없음':'로컬 조사 파일'}</div><h2>${esc(f.title)}</h2>`;let text=f.text;if(id==='F16')text=policyNotes[state.policy];if(id==='F03'||id==='F15'){const img=document.createElement('img');img.src=id==='F03'?'repair-receipt.png':'archive-box.png';img.alt=id==='F03'?'중고점의 수리 접수증. 같은 내용의 텍스트가 아래에 있습니다.':'반환 보관함의 기록 상자와 수령 확인표. 같은 내용의 텍스트가 아래에 있습니다.';img.className='evidence-photo';img.onclick=()=>showModal('사진 확대',`<img src="${img.src}" style="width:100%" alt="${esc(img.alt)}"><p class="document-text">${esc(text)}</p>`);root.append(img);const d=document.createElement('details');d.innerHTML=`<summary style="cursor:pointer;padding:12px 0">사진 속 글자 보기</summary><p class="document-text">${esc(text)}</p>`;root.append(d);}else{if(id==='F06')root.innerHTML+='<p>모든 날짜·시각은 장치가 기록한 값입니다. 실제 시각으로 보정되지 않았습니다.</p>';if(text){const p=document.createElement('p');p.className='document-text';p.textContent=text;root.append(p);}}if(f.tables?.length)root.innerHTML+=f.tables.map((t,i)=>(id==='F09'?'<h3>'+['변경 전 원본 색인','변경 후 출력물'][i]+'</h3>':'')+tableHTML(t)).join('');if(id==='F16')root.innerHTML+='<p>아직 아무 자료도 전송하지 않았습니다. 최종 검토에서 현재 방침과 전달 범위를 다시 확인할 수 있습니다.</p>';const actions=document.createElement('div');actions.className='toolbar-bottom';root.append(actions);actionButton(actions,state.pins.includes(id)?'기록보드에서 해제':'기록보드에 표시',()=>{state.pins=state.pins.includes(id)?state.pins.filter(x=>x!==id):[...state.pins,id];persist();renderWindows();});if(id==='F01')actionButton(actions,'휴지통 열기',()=>openFolder('trash'),true);if(id==='F10')actionButton(actions,state.stage===5?'전달 내용 검토':'인계 백업 확인',()=>state.stage===5?finalReview():openFolder('outbox'),true);if(id==='F13')actionButton(actions,'식별정보 처리 방침 선택',witness,true);if(id==='F16')actionButton(actions,'사건 재구성',()=>openFolder('timeline'),true);return;}
root.innerHTML=`<div class="file-meta">LOCAL ARCHIVE / ${esc(folderNames[id])}</div><h2>${esc(folderNames[id])}</h2>`;
if(id==='trash'){for(const f of ['F02','F07']){const row=document.createElement('div');row.className='timeline-card';row.innerHTML=`<strong>${F(f).title}</strong><p class="file-meta">삭제 표시 · 2026.04.19 00:12</p>`;const b=actionButton(row,state.restored.includes(f)?'복원됨':'복원',()=>restore(f),true);b.dataset.restoreFile=f;b.disabled=state.restored.includes(f);root.append(row);}return;}
if(id==='board'){if(!state.pins.length)root.innerHTML+='<p class="empty">아직 표시한 단서가 없습니다.<br>문서 아래에서 기록보드에 표시하세요.</p>';state.pins.filter(f=>accessible(f,state)).forEach(f=>fileRow(root,f));return;}
if(id==='timeline'){renderTimeline(root);return;}
if(id==='backup')root.innerHTML+='<p>보관 번호 비교 자료에 이어, 야간 반입을 확인할 세 문서를 복구했습니다.</p><p>야간직원의 메모는 작업자의 설명, 지시서는 작업을 요청한 기록, 수령 사진은 작업을 마친 기록입니다. 이 상자 한 개의 이동과 세 자료 묶음의 현재 소재는 구분해서 읽어야 합니다.</p>';
const entries={photos:['F03'],mail:['F04'],restored:state.restored,work:['F05','F06','archive'],archive:['F08','F09','outbox'],outbox:['F10','F11','F12'],backup:['F13','F14','F15',...(state.policy?['F16']:[])]}[id]||[];entries.forEach(f=>fileRow(root,f));if(!entries.length)root.innerHTML+='<p class="empty">복원한 파일이 여기에 표시됩니다.</p>';if(id==='outbox')actionButton(root,state.stage>=4?'복구한 백업 열기':'백업 검증 시작',()=>state.stage>=4?openFolder('backup'):backupPuzzle(),true);if(id==='backup')actionButton(root,state.policy?'사건 재구성':'식별정보 처리 방침 선택',()=>state.policy?openFolder('timeline'):witness(),true);
}
function restore(id){
 if(!['F02','F07'].includes(id)||state.restored.includes(id))return;
 state.restored.push(id);persist();
 document.querySelectorAll('[data-restore-file]').forEach(button=>{if(button.dataset.restoreFile===id){button.textContent='복원됨';button.disabled=true;}});
 document.querySelectorAll('[data-window-id="restored"] .window-content').forEach(content=>{const top=content.scrollTop,left=content.scrollLeft;renderContent(content,'restored');content.scrollTop=top;content.scrollLeft=left;});
 toast(F(id).title+'를 복원했습니다.');sound();
}
function renderLock(root,id,p){
 const name=folderNames[id],prompts=['접수일의 월·일을 숫자 네 자리로 입력하세요.','윤서의 실제 퇴실 시각을 24시간제 네 자리로 입력하세요.','인계 순서에 맞는 원래 번호를 연결하세요. 자료 묶음 ID로 두 문서를 비교할 수 있습니다.'];
 const w=windows.find(item=>item.id===id);
 root.innerHTML='<div class="file-meta">'+esc(name)+' / 인계 확인</div><h2>잠긴 '+esc(name)+'</h2><p>'+prompts[p]+'</p><form class="folder-unlock"><label for="work-key">확인 키</label><input id="work-key" type="text" autocomplete="off" spellcheck="false" inputmode="numeric" maxlength="30" placeholder="0000"><p class="unlock-feedback" role="status"></p><button class="primary">확인하고 열기</button></form>';
 const input=root.querySelector('#work-key'),feedback=root.querySelector('.unlock-feedback');
 input.id='unlock-key-'+id;root.querySelector('label').htmlFor=input.id;input.inputMode=p<2?'numeric':'text';input.placeholder=p<2?'0000':'ABC123';
 input.value=w.lockDraft||'';feedback.textContent=w.lockFeedback||'';
 input.oninput=()=>{w.lockDraft=input.value;};
 root.querySelector('form').onsubmit=e=>{
  e.preventDefault();if(state.stage!==p)return;
  const result=checkKey(p,input.value);
  if(!result.ok){w.lockFeedback=result.message;feedback.textContent=result.message;if(!result.format){state.attempts[p]++;persist();}return;}
  state.stage=p+1;delete w.lockDraft;delete w.lockFeedback;persist();desktop();openFolder(id);toast(name+'을 열었습니다.');
 };
}
function lock(p){if(p>state.stage){toast('먼저 이전 보관함을 복구해 주세요.');return;}const id=['work','archive','outbox'][p];if(p<state.stage){openFolder(id);return;}addWindow(id,folderNames[id]);}
function backupPuzzle(){
 if(state.stage<3){toast('먼저 발신보관함을 복구해 주세요.');return;}
 addWindow('backup',folderNames.backup);
}
function renderBackup(root){
 const d=state.backupDraft;
 root.innerHTML='<div class="file-meta">인계 백업 / 내용 검증</div><h2>백업 사본 검토</h2><p>F12 백업_목록.csv의 세 후보를 검토합니다. F11의 검토 기준과 F08의 인계 순서, F09의 변경 전후 번호를 함께 확인하세요.</p><p>오류 검사 결과와 원본 내용의 일치는 별개입니다. 각 후보의 검토 결과를 고르고, 복구할 사본을 하나 선택하세요.</p>';
 const refs=document.createElement('div');refs.className='toolbar-bottom';root.append(refs);
 for(const id of ['F11','F12','F08','F09'])actionButton(refs,id+' '+F(id).title,()=>openFile(id));
 root.insertAdjacentHTML('beforeend',`<form class="backup-form">${['r1','r2','r3'].map(k=>`<label for="backup-${k}">${k.toUpperCase()} 검토 결과</label><select id="backup-${k}" required><option value="">검토 결과 선택</option>${Object.entries(backupReasons).map(([v,t])=>`<option value="${v}" ${d[k]===v?'selected':''}>${t}</option>`).join('')}</select><p class="unlock-feedback" data-backup-error="${k}" role="status"></p>`).join('')}<label for="backup-candidate">복구할 백업</label><select id="backup-candidate" required><option value="">후보 선택</option>${['R1','R2','R3'].map(x=>`<option ${d.candidate===x?'selected':''}>${x}</option>`).join('')}</select><p class="unlock-feedback" data-backup-error="candidate" role="status"></p><button class="primary">검증하고 복구</button></form>`);
 for(const key of ['candidate','r1','r2','r3'])root.querySelector('#backup-'+key).onchange=e=>{state.backupDraft[key]=e.target.value;persist();};
 root.querySelector('form').onsubmit=e=>{
  e.preventDefault();if(state.stage!==3)return;
  root.querySelectorAll('[data-backup-error]').forEach(x=>x.textContent='');
  const errors=checkBackup(state.backupDraft);
  if(errors.length){state.attempts[3]++;persist();errors.forEach(k=>root.querySelector('[data-backup-error="'+k+'"]').textContent='이 항목을 기준 자료와 다시 비교해 주세요.');return;}
  state.stage=4;state.cpWitness=snapshot(state);persist();desktop();openFolder('backup');toast('추가 자료를 복구했습니다.');
 };
}
function witness(){if(state.stage<4){toast('먼저 인계 백업을 검증해 주세요.');return;}if(state.policy){openFile('F16');return;}if(!state.opened.includes('F13')){toast('먼저 야간 직원의 메모에서 허용 범위와 우려를 확인해 주세요.');openFile('F13');return;}showModal('증언자의 식별정보',`<p>민아는 신원 노출을 걱정하지만, 정민에게 비공개 확인 연락을 받는 방법도 허용했습니다.</p><button class="choice" id="protect"><strong>식별정보를 보호한다</strong><small>이름·계정을 W1로 바꿔 직접 식별을 줄입니다. 즉시 확인 연락하기 어렵고, 상세 작업 경로로 신원이 추정될 가능성은 남습니다.</small></button><button class="choice" id="identify"><strong>식별정보를 유지한다</strong><small>정민의 비공개 확인 연락을 위해 이름·계정을 유지합니다. 증언 확인은 쉬워지지만 수신자에게 신원이 남습니다. 외부 공개 허락은 아닙니다.</small></button><p class="muted">아직 자료를 전달하지 않습니다. 선택을 바꾸려면 증언자 선택 전으로 돌아갈 수 있습니다.</p>`,()=>{for(const policy of ['protect','identify'])modal.querySelector('#'+policy).onclick=()=>confirmAction('처리 방침 확인',policy==='protect'?'이름·계정을 W1로 바꿉니다. 직접 연락이 지연되며, 상세 경로로 신원이 추정될 가능성은 남습니다.':'민아 / BK-04를 정민의 비공개 확인 연락에 사용합니다. 다른 곳으로 공개할 수 있다는 뜻은 아닙니다.',()=>{if(state.policy||state.stage!==4||!state.opened.includes('F13'))return;state.policy=policy;persist();desktop();openFile('F16');},'이 방침으로 진행');});}
function renderTimeline(root){
 root.innerHTML+='<p>이미 확인한 시계 오차를 적용했습니다. 사건을 순서대로 놓은 뒤, 아래 세 주장을 자료와 대조하세요.</p>';
 const refs=document.createElement('div');refs.className='toolbar-bottom';root.append(refs);for(const id of refIds)actionButton(refs,`${id} ${F(id).title}`,()=>id==='F07'&&!state.restored.includes(id)?(restore(id),openFile(id)):openFile(id));
 if(state.stage===5){root.insertAdjacentHTML('beforeend',caseResolutionHTML()+'<p>아래는 제출한 결과입니다.</p>');}
 root.insertAdjacentHTML('beforeend','<h3>1. 사건 순서</h3><p class="muted" style="font-size:14px">출입기록은 +10분 보정 · 지시서와 수령 확인은 기준 시계</p><p class="feedback" id="order-error"></p>');
 let dragged=null;
 state.draft.forEach((c,index)=>{const card=document.createElement('div');card.className='timeline-card';card.draggable=state.stage<5;card.innerHTML=`<h3>${index+1}. ${events[c.id]}</h3><p>${times[c.id]}<br><small>근거: ${evidence[c.id].join(' · ')}</small></p><div class="actions"><button data-up aria-label="${events[c.id]} 위로">↑</button><button data-down aria-label="${events[c.id]} 아래로">↓</button></div>`;root.append(card);const move=target=>{if(state.stage>=5||target<0||target>=5)return;const item=state.draft.splice(index,1)[0];state.draft.splice(target,0,item);persist();renderWindows();};for(const [key,delta] of [['up',-1],['down',1]]){const b=card.querySelector('[data-'+key+']');b.disabled=state.stage===5||index+delta<0||index+delta>=5;b.onclick=()=>move(index+delta);}card.ondragstart=e=>{dragged=c.id;e.dataTransfer.setData('text/plain',String(c.id));};card.ondragover=e=>{if(state.stage<5)e.preventDefault();};card.ondrop=e=>{e.preventDefault();if(dragged===null||state.stage>=5)return;const from=state.draft.findIndex(x=>x.id===dragged);if(from<0)return;const item=state.draft.splice(from,1)[0];state.draft.splice(index,0,item);dragged=null;persist();renderWindows();};});
 const h=document.createElement('h3');h.textContent='2. 주장 검토';root.append(h);const notice=document.createElement('p');notice.textContent='다음 문장들은 원문 인용이 아닌 조사용 가설입니다. 각 판단에 사용한 자료를 표시하세요. 판단 불가는 사실이 없다는 뜻이 아니라, 읽은 자료로 그 주장까지 확정할 수 없다는 뜻입니다. 이때도 자료가 확인해 주는 범위를 근거로 선택합니다.';root.append(notice);
 state.claims.forEach((c,i)=>{
  const card=document.createElement('div');card.className='timeline-card';card.dataset.claim=i;
  card.innerHTML=`<h3>Q${i+1}. ${esc(claimTexts[i])}</h3><label>판정<select data-judgment ${state.stage===5?'disabled':''}><option value="">판정 선택</option>${Object.entries(judgments).map(([v,t])=>`<option value="${v}" ${c.judgment===v?'selected':''}>${t}</option>`).join('')}</select></label><p>이 판정에 사용한 자료</p><div class="claim-refs">${refIds.map(f=>`<label><input type="checkbox" data-ref="${f}" ${c.refs.includes(f)?'checked':''} ${state.stage===5||!accessible(f,state)?'disabled':''}> ${f} ${esc(F(f).title)}</label>`).join('')}</div><div data-reason-wrap ${c.judgment==='undetermined'?'':'hidden'}><label>판단 불가를 선택한 이유<select data-reason ${state.stage===5||c.judgment!=='undetermined'?'disabled':''}><option value="">이유 선택</option>${Object.entries(claimReasons).map(([v,t])=>`<option value="${v}" ${c.reason===v?'selected':''}>${t}</option>`).join('')}</select></label></div><p class="unlock-feedback" data-claim-error role="status"></p>`;
  root.append(card);
  const reason=card.querySelector('[data-reason]'),reasonWrap=card.querySelector('[data-reason-wrap]');
  card.querySelector('[data-judgment]').onchange=e=>{
   c.judgment=e.target.value;reasonWrap.hidden=c.judgment!=='undetermined';reason.disabled=reasonWrap.hidden;
   if(reasonWrap.hidden){c.reason='';reason.value='';}persist();
  };
  card.querySelectorAll('[data-ref]').forEach(b=>b.onchange=()=>{c.refs=b.checked?[...new Set([...c.refs,b.dataset.ref])]:c.refs.filter(x=>x!==b.dataset.ref);persist();});
  reason.onchange=e=>{c.reason=e.target.value;persist();};
 });

 actionButton(root,state.stage===5?'전달 단계로 이동':'사건 재구성 검토',()=>{if(state.stage===5){handoffAction();return;}if(state.stage!==4||!state.policy)return;if(state.claims.some(c=>!c.judgment||!c.refs.length||(c.judgment==='undetermined'&&!c.reason))){toast('각 주장의 판정과 근거를 선택하고, 판단 불가인 항목에는 이유도 선택해 주세요.');return;}root.querySelectorAll('[data-claim-error],#order-error').forEach(x=>x.textContent='');const errors=checkTimeline(state.draft,state.claims);if(errors.length){state.attempts[4]++;persist();for(const e of errors){const target=e.id==='order'?root.querySelector('#order-error'):root.querySelector(`[data-claim="${e.id}"] [data-claim-error]`);target.textContent=e.message;}toast('표시된 항목을 다시 확인하세요. 작성한 내용은 유지됩니다.');return;}state.stage=5;persist();desktop();toast('지시 전 퇴실과 번호 변경을 확인했습니다. 계정 기록만으로 모든 책임을 확정하지는 않습니다.');},true);
}
function finalReview(){if(state.stage!==5||!state.policy)return;if(!state.opened.includes('F10')){toast('먼저 마지막 메일을 확인해 주세요.');openFile('F10');return;}const pending=['F02','F07'].filter(f=>!state.restored.includes(f));try{state=prepareHandoff(state);}catch(e){toast(e.message);return;}persist();desktop();if(pending.length)toast('전달에 필요한 조각을 복원했습니다: '+pending.join(', '));const protectedCopy=state.policy==='protect';showModal('마지막 인계 검토',`<div class="eyebrow">LOCAL HANDOFF · 최종 선택</div><p>수신자: 정민<br><span class="mono">handoff@corner.invalid</span></p><span class="chip">${protectedCopy?'식별정보 치환 사본 · 증언자 W1':'비공개 확인 연락 · 민아 / BK-04'}</span><p>${protectedCopy?'직접 식별정보를 줄입니다. 바로 확인 연락하기는 어렵고 상세 경로로 신원이 추정될 가능성은 남습니다.':'허용된 비공개 연락을 위해 이름과 계정을 유지합니다. 다른 곳에 공개할 수 있다는 뜻은 아닙니다.'}</p><button class="choice" id="full"><strong>검증 자료묶음 전달</strong><small>F08·F09 비교 기록, F06·F07 시간 근거, F13~F15 증언·지시·수령, F10·F16 인계 경위와 사건 재구성을 전달합니다. 검토를 지금 시작할 수 있지만 상세 작업 경로도 수신자에게 남습니다.</small></button><button class="choice" id="summary"><strong>요약만 전달</strong><small>상세 시각·경로·첨부를 제외한 접수 요약입니다. 전달 범위와 연락을 먼저 확인하고, 원본 대조는 다음 인계까지 보류합니다.</small></button><button id="preview-copy">전달 사본 미리보기</button><p class="muted" style="font-size:13px">게임 속 인계입니다. 실제 메일이나 파일은 전송되지 않습니다.</p>`,()=>{for(const choice of ['full','summary'])modal.querySelector('#'+choice).onclick=()=>confirmAction('이대로 전달할까요?',`${protectedCopy?'식별정보 보호 · W1':'비공개 확인을 위한 식별정보 유지'}\n${choice==='full'?'자료묶음: 기록 검토를 시작하며 상세 작업 경로도 전달됩니다.':'접수 요약: 세부 시각·경로·첨부 없이 전달 범위부터 확인합니다. 원본 대조는 보류됩니다.'}`,()=>{if(!canFinalize(state)){toast('인계 준비 상태를 확인해 주세요.');return;}state.choice=choice;state.ending=endingFor(state.policy,choice);state.endingsSeen=[...new Set([...state.endingsSeen,state.ending])];persist();renderEnding();},'이대로 전달');modal.querySelector('#preview-copy').onclick=previewCopy;});}
function previewCopy(){const protect=state.policy==='protect',transform=s=>protect?s.replaceAll('민아','증언자 W1').replaceAll('BK-04','증언자 W1'):s;showModal('전달 사본 미리보기',`<span class="chip">${protect?'식별정보 치환 사본':'식별정보 유지 · 비공개 확인용'}</span><h3>요약만 선택할 때</h3><p style="white-space:pre-line">${esc(summaryFor(state.policy))}</p><p>세부 시각·작업 경로·원본 번호·첨부자료는 포함하지 않습니다.</p><h3>자료묶음을 선택할 때만 추가</h3>${['F08','F09','F06','F07','F13','F14','F15','F10','F16'].map(id=>`<details><summary>${esc(F(id).title)}</summary><p style="white-space:pre-line">${esc(transform(id==='F16'?policyNotes[state.policy]:F(id).text))}</p>${(F(id).tables||[]).map(t=>tableHTML(t.map(row=>row.map(transform)))).join('')}</details>`).join('')}<details><summary>사건 재구성 결과</summary>${tableHTML([['시각','사건'],...events.map((e,i)=>[times[i],e])])}${state.claims.map((c,i)=>`<p>Q${i+1}: ${esc(claimTexts[i])}<br>${judgments[c.judgment]} · ${c.refs.join(' / ')}</p>`).join('')}<p>${claimReasons[state.claims[2].reason]}</p></details><button class="primary" id="back-final">최종 검토로 돌아가기</button>`,()=>modal.querySelector('#back-final').onclick=finalReview);}
function caseResolutionHTML(){return '<section class="case-resolution"><h3>이번 조사로 밝혀진 사실</h3><ol>'+caseResolution.facts.map(f=>'<li>'+esc(f)+'</li>').join('')+'</ol><p>'+esc(caseResolution.limit)+'</p></section>';}
function renderEnding(){view='ending';if(modal.open)modal.close();const e=endings.find(e=>e.id===state.ending);app.innerHTML=`<main class="start"><header class="topline"><span>EPISODE 01 / 조사 완료</span><span class="chip">발견한 결말 ${state.endingsSeen.length} / 4</span></header><article class="ending"><div class="eyebrow">REPLY FROM 정민 · 게임 속 답신</div><h1>${esc(e.title)}</h1><p class="muted">정민 &lt;handoff@corner.invalid&gt;</p><blockquote>${esc(e.text)}</blockquote><p class="muted">아래는 당신이 컴퓨터에 남긴 조사 기록입니다. 정민에게 전달된 자료의 범위는 위 답신에 적혀 있습니다.</p>${caseResolutionHTML()}<h3>컴퓨터가 당신에게 온 이유</h3><p style="line-height:2">${esc(commonAfterword)}</p><h3>이후의 기록 — ${esc(e.followTitle)}</h3><blockquote>${esc(e.follow)}</blockquote><div class="actions">${e.status.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><p style="color:var(--accent);line-height:1.9;margin:28px 0">${esc(e.last)}</p><div class="actions"><button class="primary" id="replay-final">마지막 선택 다시 보기</button><button id="replay-witness">증언자 선택부터 다시 보기</button><button id="explain">사건 해설</button><button id="home-ending">시작 화면</button></div></article></main>`;document.querySelector('#replay-final').onclick=()=>replay('cpFinal');document.querySelector('#replay-witness').onclick=()=>confirmAction('증언자 선택으로 돌아가기','이후의 신원 방침과 주장 검토를 다시 진행합니다. 이미 본 엔딩 기록은 유지됩니다.',()=>replay('cpWitness'));document.querySelector('#explain').onclick=explain;document.querySelector('#home-ending').onclick=start;}
function replay(key){const cp=state[key];if(!cp){toast('복귀 지점을 찾지 못했습니다.');return;}const settings=state.settings,seen=state.endingsSeen,witnessCP=state.cpWitness;state={...fresh(seen),...structuredClone(cp),settings,endingsSeen:seen,cpWitness:witnessCP,cpFinal:key==='cpFinal'?cp:null,choice:null,ending:null};if(key==='cpWitness'){state.policy=null;state.stage=4;state.handoffPrepared=false;state.pins=state.pins.filter(x=>x!=='F16');state.opened=state.opened.filter(x=>x!=='F16');state.draft=fresh().draft;state.claims=fresh().claims;}windows=[];persist();desktop();key==='cpFinal'?finalReview():witness();}
function explain(){showModal('그날 밤의 기록',`<p>${esc(commonAfterword)}</p><p>접수일은 4월 17일이며 장치는 10분 느렸습니다. F08의 PK-31 → PK-12 → PK-27을 원본 색인과 연결하면 A2·C4·D6입니다. R1은 순번 중복, R3은 원본 D6이 D0으로 덮여 있어 R2를 선택합니다.</p>${tableHTML([['실제 시각','사건'],...events.map((e,i)=>[times[i],e])])}${caseResolutionHTML()}<p>Q3에서는 F06의 실행 계정, F09의 승인 계정 또는 F14의 발행 계정을 근거로 사용할 수 있습니다. 이 자료들은 ADM이라는 계정의 흔적을 보여주지만 실제 사용자를 특정하지 못합니다. F07은 시계 보정 자료이므로 계정 사용자를 판단하는 필수 근거는 아닙니다.</p><p>현재 선택은 ${state.policy==='protect'?'신원 직접 전달을 줄이되 확인 연락이 지연되는 방침':'허용된 비공개 연락을 위해 신원을 유지하는 방침'}과 ${state.choice==='full'?'상세 경로를 포함해 기록 검토를 시작하는 인계':'상세 자료를 남겨 두고 전달 범위부터 확인하는 인계'}입니다.</p><button id="all-endings">전체 분기 해설 보기 · 스포일러</button><div id="branches"></div>`,()=>modal.querySelector('#all-endings').onclick=()=>{modal.querySelector('#branches').innerHTML=tableHTML([['식별정보','전달 범위','결말'],...endings.map(e=>[e.id==='A'||e.id==='B'?'유지':'보호',e.id==='A'||e.id==='C'?'자료묶음':'요약',e.id+' · '+e.title])]);});}
window.addEventListener('storage',e=>{if(e.key!==KEY)return;conflict=true;updateStatus();showModal('다른 탭에서 진행이 바뀌었습니다',`<p>추가 저장을 일시 중단했습니다. 사용할 진행을 선택해 주세요.</p><div class="actions"><button class="primary" id="load-latest">최신 진행 불러오기</button><button id="overwrite">현재 진행으로 덮어쓰기</button></div>`,()=>{modal.querySelector('#load-latest').onclick=()=>{try{const raw=localStorage.getItem(KEY);state=raw?validate(JSON.parse(raw)):fresh();conflict=false;loadIssue='';windows=[];modal.close();start();toast('최신 진행을 불러왔습니다.');}catch{toast('최신 저장을 읽을 수 없습니다. 현재 진행은 유지됩니다.');}};modal.querySelector('#overwrite').onclick=()=>{conflict=false;loadIssue='';persist();modal.close();};});});
window.addEventListener('resize',()=>{if(view==='desktop')renderWindows();});
document.addEventListener('visibilitychange',()=>{if(document.hidden)audioContext?.suspend();else audioContext?.resume();});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_investigation_progress',title:'조사 진행 확인',description:'현재 목표, 접근 가능한 조사 파일, 해결한 퍼즐 수를 확인합니다. 정답이나 미열람 결말을 공개하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(input&&Object.keys(input).length)throw Error('입력값이 필요하지 않습니다.');return {started:state.started,solvedPuzzles:state.stage,goal:currentGoal(),availableFiles:files.filter(f=>accessible(f.id,state)).map(f=>({id:f.id,title:f.title})),endingsSeen:state.endingsSeen.length};}})).catch(()=>{});}catch{}}
start();









